Dataset exploration

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf 
from PIL import Image 
import os
from sklearn.model_selection import train_test_split 
from keras.utils import to_categorical
from keras.models import Sequential 
from keras.layers import Conv2D, MaxPool2D, Dense, Flatten, Dropout
data = []
labels=[]

In [2]:
classes = 43 
cur_path = os.getcwd() 
for i in range(classes): 
  path = os. path.join(cur_path,'train', str(i)) 
  images = os.listdir(path)
   
    
  for a in images: 
   
    image = Image.open(path +'/'+ a) 
    image = image.resize((30,30)) 
    image = np.array(image) 
    data.append(image) 
    labels.append(i) 
     

data = np.array(data)
labels = np.array(labels)

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'd:\\Artificial_Intelligence\\AI\\ARTIFICIAL_INTELLIGENCE - Copy\\Deep_Learning\\Trafic_Signal_Recognition\\train\\0'

In [ ]:
#Splitting training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, random_state=42)
print(X_train.shape, X_train.shape, y_train.shape, y_train.shape)

(31367, 30, 30, 3) (31367, 30, 30, 3) (31367,) (31367,)


In [ ]:
y_train

array([36, 28,  2, ..., 39,  1, 10])

In [ ]:
y_train = to_categorical(y_train, 43)
y_test = to_categorical(y_test, 43)

CNN model building

In [ ]:
#Building the model
model = Sequential()
model.add(Conv2D(filters=32, kernel_size=(5,5), activation='relu', input_shape=X_train.shape[1:]))
model.add(Conv2D(filters=32, kernel_size=(5,5), activation='relu'))
model.add(MaxPool2D(pool_size=(2, 2)))
model.add(Dropout(rate=0.25))
model.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
model.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
model.add(MaxPool2D(pool_size=(2, 2)))
model.add(Dropout(rate=0.25))
model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(rate=0.5))
model.add(Dense(43, activation='softmax'))
#Compilation of the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

Model training and validation

In [ ]:
eps = 15
anc = model.fit(X_train, y_train, batch_size=32, epochs=eps, validation_data=(X_test, y_test))

Epoch 1/15
981/981 [==============================] - 55s 56ms/step - loss: 2.1384 - accuracy: 0.4359 - val_loss: 0.6848 - val_accuracy: 0.8182
Epoch 2/15
981/981 [==============================] - 59s 60ms/step - loss: 0.7275 - accuracy: 0.7846 - val_loss: 0.2543 - val_accuracy: 0.9244
Epoch 3/15
981/981 [==============================] - 60s 61ms/step - loss: 0.4405 - accuracy: 0.8704 - val_loss: 0.1861 - val_accuracy: 0.9417
Epoch 4/15
981/981 [==============================] - 59s 61ms/step - loss: 0.3142 - accuracy: 0.9082 - val_loss: 0.1088 - val_accuracy: 0.9694
Epoch 5/15
981/981 [==============================] - 60s 61ms/step - loss: 0.2793 - accuracy: 0.9211 - val_loss: 0.1302 - val_accuracy: 0.9689
Epoch 6/15
981/981 [==============================] - 61s 62ms/step - loss: 0.2565 - accuracy: 0.9283 - val_loss: 0.0931 - val_accuracy: 0.9760
Epoch 7/15
981/981 [==============================] - 60s 61ms/step - loss: 0.2450 - accuracy: 0.9327 - val_loss: 0.0727 - val_accuracy:

In [ ]:
eps = 15
history = model.fit(X_train, y_train, batch_size=64, epochs=eps, validation_data=(X_test, y_test))

Epoch 1/15
491/491 [==============================] - 49s 100ms/step - loss: 0.1428 - accuracy: 0.9628 - val_loss: 0.0361 - val_accuracy: 0.9911
Epoch 2/15
491/491 [==============================] - 57s 116ms/step - loss: 0.1169 - accuracy: 0.9693 - val_loss: 0.0535 - val_accuracy: 0.9884
Epoch 3/15
491/491 [==============================] - 63s 129ms/step - loss: 0.1188 - accuracy: 0.9688 - val_loss: 0.0521 - val_accuracy: 0.9883
Epoch 4/15
491/491 [==============================] - 63s 128ms/step - loss: 0.1195 - accuracy: 0.9669 - val_loss: 0.0591 - val_accuracy: 0.9846
Epoch 5/15
491/491 [==============================] - 62s 126ms/step - loss: 0.1462 - accuracy: 0.9629 - val_loss: 0.0331 - val_accuracy: 0.9916
Epoch 6/15
491/491 [==============================] - 59s 121ms/step - loss: 0.1288 - accuracy: 0.9672 - val_loss: 0.0371 - val_accuracy: 0.9911
Epoch 7/15
491/491 [==============================] - 55s 113ms/step - loss: 0.1141 - accuracy: 0.9699 - val_loss: 0.0379 - val_ac

In [ ]:
model.save('traffic_classifier.h5') #to save

In [ ]:
import tkinter as tk
from tkinter import filedialog
from tkinter import *
from PIL import ImageTk, Image
import numpy
from keras.models import load_model
import numpy as np
model = load_model('traffic_classifier.h5')
#dictionary to label all traffic signs class.
classes = { 1:'Speed limit (20km/h)',
           2:'Speed limit (30km/h)',
           3:'Speed limit (50km/h)',
           4:'Speed limit (60km/h)',
           5:'Speed limit (70km/h)',
           6:'Speed limit (80km/h)',
           7:'End of speed limit (80km/h)',
           8:'Speed limit (100km/h)',
           9:'Speed limit (120km/h)',
           10:'No passing',
           11:'No passing veh over 3.5 tons',
           12:'Right-of-way at intersection',
           13:'Priority road',
           14:'Yield',
           15:'Stop',
           16:'No vehicles',
           17:'Veh > 3.5 tons prohibited',
           18:'No entry',
           19:'General caution',
           20:'Dangerous curve left',
           21:'Dangerous curve right',
           22:'Double curve',
           23:'Bumpy road',
           24:'Slippery road',
           25:'Road narrows on the right',
           26:'Road work',
           27:'Traffic signals',
           28:'Pedestrians',
           29:'Children crossing',
           30:'Bicycles crossing',
           31:'Beware of ice/snow',
           32:'Wild animals crossing',
           33:'End speed + passing limits',
           34:'Turn right ahead',
           35:'Turn left ahead',
           36:'Ahead only',
           37:'Go straight or right',
           38:'Go straight or left',
           39:'Keep right',
           40:'Keep left',
           41:'Roundabout mandatory',
           42:'End of no passing',
           43:'End no passing vehicle with a weight greater than 3.5 tons' }



In [ ]:
#initialise GUI
import cv2 as cv
top=tk.Tk()
top.geometry('800x600')
top.title('Traffic sign classification')
top.configure(background='#CDCDCD')
label=Label(top,background='#CDCDCD', font=('arial',15,'bold'))
sign_image = Label(top)

def classify(file_path):
   global label_packed
   # image = Image.open(file_path)
   # image = image.resize((30,30))
   # image=image.reshape(None,30,30,3)
   image=cv.imread(file_path)
   image=cv.resize(image,(30,30))
   image=image.reshape(30,30,3)
   print(image)
   print("******************")
   image = np.expand_dims(image, axis=0)
   
#    image=np.array(image)[image.astype(int)]
   image = np.array(image)
   print(image)
   # image.image
   
   # image = np.array(image) 
   pred = np.argmax(model.predict(image), axis=1)
   print(pred)
   print("***************")
   # pred =np.array(pred)[pred.astype(int)]
   type(pred)
   print(pred)
   sign = classes[int(pred[0])+1]
   print(sign)
   label.configure(foreground='#011638', text=sign)

def show_classify_button(file_path):
   classify_b=Button(top,text="Classify Image",command=lambda: classify(file_path),padx=10,pady=5)
   classify_b.configure(background='#364156', foreground='white',font=('arial',10,'bold'))
   classify_b.place(relx=0.79,rely=0.46)

def upload_image():
    try:
        file_path=filedialog.askopenfilename()
        uploaded=Image.open(file_path)
        uploaded.thumbnail(((top.winfo_width()/2.25),(top.winfo_height()/2.25)))
        im=ImageTk.PhotoImage(uploaded)
        sign_image.configure(image=im)
        sign_image.image=im
        label.configure(text='')
        show_classify_button(file_path)
    except:
        pass
upload=Button(top,text="Upload an image",command=upload_image,padx=10,pady=5)
upload.configure(background='#364156', foreground='white',font=('arial',10,'bold'))
upload.pack(side=BOTTOM,pady=50)
sign_image.pack(side=BOTTOM,expand=True)
label.pack(side=BOTTOM,expand=True)
heading = Label(top, text="check traffic sign",pady=20, font=('arial',20,'bold'))
heading.configure(background='#CDCDCD',foreground='#364156')
heading.pack()
top.mainloop()


[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [112 125 132]
  [114 128 138]
  [112 128 138]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [117 134 140]
  [109 124 135]
  [115 128 135]]

 [[255 255 254]
  [255 255 255]
  [255 255 255]
  ...
  [108 126 132]
  [112 127 136]
  [114 127 135]]]
******************
[[[[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  ...

  [[255 255